/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthAuthCallbackRouteImport } from './routes/auth/AuthCallback'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/ForgotPassword'
import { Route as AuthLoginRouteImport } from './routes/auth/Login'
import { Route as AuthOtpRouteImport } from './routes/auth/Otp'
import { Route as AuthPasskeySettingsRouteImport } from './routes/auth/PasskeySettings'
import { Route as AuthRegisterRouteImport } from './routes/auth/Register'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/ResetPassword'

const AuthAuthCallbackRoute = AuthAuthCallbackRouteImport.update({
  id: '/auth/AuthCallback',
  path: '/auth/AuthCallback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/ForgotPassword',
  path: '/auth/ForgotPassword',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/Login',
  path: '/auth/Login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/auth/Otp',
  path: '/auth/Otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPasskeySettingsRoute = AuthPasskeySettingsRouteImport.update({
  id: '/auth/PasskeySettings',
  path: '/auth/PasskeySettings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/Register',
  path: '/auth/Register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/ResetPassword',
  path: '/auth/ResetPassword',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/auth/AuthCallback': typeof AuthAuthCallbackRoute
  '/auth/ForgotPassword': typeof AuthForgotPasswordRoute
  '/auth/Login': typeof AuthLoginRoute
  '/auth/Otp': typeof AuthOtpRoute
  '/auth/PasskeySettings': typeof AuthPasskeySettingsRoute
  '/auth/Register': typeof AuthRegisterRoute
  '/auth/ResetPassword': typeof AuthResetPasswordRoute
}
export interface FileRoutesByTo {
  '/auth/AuthCallback': typeof AuthAuthCallbackRoute
  '/auth/ForgotPassword': typeof AuthForgotPasswordRoute
  '/auth/Login': typeof AuthLoginRoute
  '/auth/Otp': typeof AuthOtpRoute
  '/auth/PasskeySettings': typeof AuthPasskeySettingsRoute
  '/auth/Register': typeof AuthRegisterRoute
  '/auth/ResetPassword': typeof AuthResetPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth/AuthCallback': typeof AuthAuthCallbackRoute
  '/auth/ForgotPassword': typeof AuthForgotPasswordRoute
  '/auth/Login': typeof AuthLoginRoute
  '/auth/Otp': typeof AuthOtpRoute
  '/auth/PasskeySettings': typeof AuthPasskeySettingsRoute
  '/auth/Register': typeof AuthRegisterRoute
  '/auth/ResetPassword': typeof AuthResetPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth/AuthCallback'
    | '/auth/ForgotPassword'
    | '/auth/Login'
    | '/auth/Otp'
    | '/auth/PasskeySettings'
    | '/auth/Register'
    | '/auth/ResetPassword'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/AuthCallback'
    | '/auth/ForgotPassword'
    | '/auth/Login'
    | '/auth/Otp'
    | '/auth/PasskeySettings'
    | '/auth/Register'
    | '/auth/ResetPassword'
  id:
    | '__root__'
    | '/auth/AuthCallback'
    | '/auth/ForgotPassword'
    | '/auth/Login'
    | '/auth/Otp'
    | '/auth/PasskeySettings'
    | '/auth/Register'
    | '/auth/ResetPassword'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthAuthCallbackRoute: typeof AuthAuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthPasskeySettingsRoute: typeof AuthPasskeySettingsRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth/AuthCallback': {
      id: '/auth/AuthCallback'
      path: '/auth/AuthCallback'
      fullPath: '/auth/AuthCallback'
      preLoaderRoute: typeof AuthAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/ForgotPassword': {
      id: '/auth/ForgotPassword'
      path: '/auth/ForgotPassword'
      fullPath: '/auth/ForgotPassword'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/Login': {
      id: '/auth/Login'
      path: '/auth/Login'
      fullPath: '/auth/Login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/Otp': {
      id: '/auth/Otp'
      path: '/auth/Otp'
      fullPath: '/auth/Otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/PasskeySettings': {
      id: '/auth/PasskeySettings'
      path: '/auth/PasskeySettings'
      fullPath: '/auth/PasskeySettings'
      preLoaderRoute: typeof AuthPasskeySettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/Register': {
      id: '/auth/Register'
      path: '/auth/Register'
      fullPath: '/auth/Register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/ResetPassword': {
      id: '/auth/ResetPassword'
      path: '/auth/ResetPassword'
      fullPath: '/auth/ResetPassword'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthAuthCallbackRoute: AuthAuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthPasskeySettingsRoute: AuthPasskeySettingsRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
